// Copyright 2025 layfellow. All rights reserved.
// Use of this source code is governed by an MIT license
// that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: util/todoist.proto

package util

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PbDuration represents a task's duration in the cache
type PbDuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbDuration) Reset() {
	*x = PbDuration{}
	mi := &file_util_todoist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbDuration) ProtoMessage() {}

func (x *PbDuration) ProtoReflect() protoreflect.Message {
	mi := &file_util_todoist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbDuration.ProtoReflect.Descriptor instead.
func (*PbDuration) Descriptor() ([]byte, []int) {
	return file_util_todoist_proto_rawDescGZIP(), []int{0}
}

func (x *PbDuration) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PbDuration) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// PbDue represents a task's due date in the cache
type PbDue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	IsRecurring   bool                   `protobuf:"varint,2,opt,name=is_recurring,json=isRecurring,proto3" json:"is_recurring,omitempty"`
	DueString     string                 `protobuf:"bytes,3,opt,name=due_string,json=dueString,proto3" json:"due_string,omitempty"` // Renamed from 'string' to avoid conflict
	Datetime      string                 `protobuf:"bytes,4,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Timezone      string                 `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbDue) Reset() {
	*x = PbDue{}
	mi := &file_util_todoist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbDue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbDue) ProtoMessage() {}

func (x *PbDue) ProtoReflect() protoreflect.Message {
	mi := &file_util_todoist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbDue.ProtoReflect.Descriptor instead.
func (*PbDue) Descriptor() ([]byte, []int) {
	return file_util_todoist_proto_rawDescGZIP(), []int{1}
}

func (x *PbDue) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PbDue) GetIsRecurring() bool {
	if x != nil {
		return x.IsRecurring
	}
	return false
}

func (x *PbDue) GetDueString() string {
	if x != nil {
		return x.DueString
	}
	return ""
}

func (x *PbDue) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *PbDue) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

// PbProject represents a Todoist project in the cache
type PbProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	ViewStyle     string                 `protobuf:"bytes,5,opt,name=view_style,json=viewStyle,proto3" json:"view_style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbProject) Reset() {
	*x = PbProject{}
	mi := &file_util_todoist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbProject) ProtoMessage() {}

func (x *PbProject) ProtoReflect() protoreflect.Message {
	mi := &file_util_todoist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbProject.ProtoReflect.Descriptor instead.
func (*PbProject) Descriptor() ([]byte, []int) {
	return file_util_todoist_proto_rawDescGZIP(), []int{2}
}

func (x *PbProject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PbProject) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *PbProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PbProject) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *PbProject) GetViewStyle() string {
	if x != nil {
		return x.ViewStyle
	}
	return ""
}

// PbSection represents a Todoist section in the cache
type PbSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Collapsed     bool                   `protobuf:"varint,4,opt,name=collapsed,proto3" json:"collapsed,omitempty"`
	Order         int32                  `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbSection) Reset() {
	*x = PbSection{}
	mi := &file_util_todoist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbSection) ProtoMessage() {}

func (x *PbSection) ProtoReflect() protoreflect.Message {
	mi := &file_util_todoist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbSection.ProtoReflect.Descriptor instead.
func (*PbSection) Descriptor() ([]byte, []int) {
	return file_util_todoist_proto_rawDescGZIP(), []int{3}
}

func (x *PbSection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PbSection) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PbSection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PbSection) GetCollapsed() bool {
	if x != nil {
		return x.Collapsed
	}
	return false
}

func (x *PbSection) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

// PbItem represents a Todoist task/item in the cache
type PbItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	SectionId     string                 `protobuf:"bytes,3,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	ChildOrder    int32                  `protobuf:"varint,7,opt,name=child_order,json=childOrder,proto3" json:"child_order,omitempty"`
	Collapsed     bool                   `protobuf:"varint,8,opt,name=collapsed,proto3" json:"collapsed,omitempty"`
	Labels        []string               `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty"`
	Duration      *PbDuration            `protobuf:"bytes,10,opt,name=duration,proto3" json:"duration,omitempty"`
	Due           *PbDue                 `protobuf:"bytes,11,opt,name=due,proto3" json:"due,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbItem) Reset() {
	*x = PbItem{}
	mi := &file_util_todoist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbItem) ProtoMessage() {}

func (x *PbItem) ProtoReflect() protoreflect.Message {
	mi := &file_util_todoist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbItem.ProtoReflect.Descriptor instead.
func (*PbItem) Descriptor() ([]byte, []int) {
	return file_util_todoist_proto_rawDescGZIP(), []int{4}
}

func (x *PbItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PbItem) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PbItem) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *PbItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PbItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PbItem) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PbItem) GetChildOrder() int32 {
	if x != nil {
		return x.ChildOrder
	}
	return 0
}

func (x *PbItem) GetCollapsed() bool {
	if x != nil {
		return x.Collapsed
	}
	return false
}

func (x *PbItem) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PbItem) GetDuration() *PbDuration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *PbItem) GetDue() *PbDue {
	if x != nil {
		return x.Due
	}
	return nil
}

func (x *PbItem) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

// PbLabel represents a Todoist label in the cache
type PbLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbLabel) Reset() {
	*x = PbLabel{}
	mi := &file_util_todoist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbLabel) ProtoMessage() {}

func (x *PbLabel) ProtoReflect() protoreflect.Message {
	mi := &file_util_todoist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbLabel.ProtoReflect.Descriptor instead.
func (*PbLabel) Descriptor() ([]byte, []int) {
	return file_util_todoist_proto_rawDescGZIP(), []int{5}
}

func (x *PbLabel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PbLabel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PbLabel) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// PbComment represents a Todoist comment (note) in the cache
type PbComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbComment) Reset() {
	*x = PbComment{}
	mi := &file_util_todoist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbComment) ProtoMessage() {}

func (x *PbComment) ProtoReflect() protoreflect.Message {
	mi := &file_util_todoist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbComment.ProtoReflect.Descriptor instead.
func (*PbComment) Descriptor() ([]byte, []int) {
	return file_util_todoist_proto_rawDescGZIP(), []int{6}
}

func (x *PbComment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PbComment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PbComment) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PbComment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// CachedTodoistData is the main cache structure
type CachedTodoistData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncToken     string                 `protobuf:"bytes,1,opt,name=sync_token,json=syncToken,proto3" json:"sync_token,omitempty"`
	CachedAt      int64                  `protobuf:"varint,2,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at,omitempty"`
	Projects      []*PbProject           `protobuf:"bytes,3,rep,name=projects,proto3" json:"projects,omitempty"`
	Sections      []*PbSection           `protobuf:"bytes,4,rep,name=sections,proto3" json:"sections,omitempty"`
	Items         []*PbItem              `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	Labels        []*PbLabel             `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	Comments      []*PbComment           `protobuf:"bytes,7,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CachedTodoistData) Reset() {
	*x = CachedTodoistData{}
	mi := &file_util_todoist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedTodoistData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedTodoistData) ProtoMessage() {}

func (x *CachedTodoistData) ProtoReflect() protoreflect.Message {
	mi := &file_util_todoist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedTodoistData.ProtoReflect.Descriptor instead.
func (*CachedTodoistData) Descriptor() ([]byte, []int) {
	return file_util_todoist_proto_rawDescGZIP(), []int{7}
}

func (x *CachedTodoistData) GetSyncToken() string {
	if x != nil {
		return x.SyncToken
	}
	return ""
}

func (x *CachedTodoistData) GetCachedAt() int64 {
	if x != nil {
		return x.CachedAt
	}
	return 0
}

func (x *CachedTodoistData) GetProjects() []*PbProject {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *CachedTodoistData) GetSections() []*PbSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *CachedTodoistData) GetItems() []*PbItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CachedTodoistData) GetLabels() []*PbLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CachedTodoistData) GetComments() []*PbComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

var File_util_todoist_proto protoreflect.FileDescriptor

const file_util_todoist_proto_rawDesc = "" +
	"\n" +
	"\x12util/todoist.proto\x12\x04util\"8\n" +
	"\n" +
	"PbDuration\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\"\x95\x01\n" +
	"\x05PbDue\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12!\n" +
	"\fis_recurring\x18\x02 \x01(\bR\visRecurring\x12\x1d\n" +
	"\n" +
	"due_string\x18\x03 \x01(\tR\tdueString\x12\x1a\n" +
	"\bdatetime\x18\x04 \x01(\tR\bdatetime\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\"\x81\x01\n" +
	"\tPbProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x1d\n" +
	"\n" +
	"view_style\x18\x05 \x01(\tR\tviewStyle\"\x82\x01\n" +
	"\tPbSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tcollapsed\x18\x04 \x01(\bR\tcollapsed\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x05R\x05order\"\xf5\x02\n" +
	"\x06PbItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x03 \x01(\tR\tsectionId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vchild_order\x18\a \x01(\x05R\n" +
	"childOrder\x12\x1c\n" +
	"\tcollapsed\x18\b \x01(\bR\tcollapsed\x12\x16\n" +
	"\x06labels\x18\t \x03(\tR\x06labels\x12,\n" +
	"\bduration\x18\n" +
	" \x01(\v2\x10.util.PbDurationR\bduration\x12\x1d\n" +
	"\x03due\x18\v \x01(\v2\v.util.PbDueR\x03due\x12!\n" +
	"\fcompleted_at\x18\f \x01(\tR\vcompletedAt\"C\n" +
	"\aPbLabel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"m\n" +
	"\tPbComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"\xa1\x02\n" +
	"\x11CachedTodoistData\x12\x1d\n" +
	"\n" +
	"sync_token\x18\x01 \x01(\tR\tsyncToken\x12\x1b\n" +
	"\tcached_at\x18\x02 \x01(\x03R\bcachedAt\x12+\n" +
	"\bprojects\x18\x03 \x03(\v2\x0f.util.PbProjectR\bprojects\x12+\n" +
	"\bsections\x18\x04 \x03(\v2\x0f.util.PbSectionR\bsections\x12\"\n" +
	"\x05items\x18\x05 \x03(\v2\f.util.PbItemR\x05items\x12%\n" +
	"\x06labels\x18\x06 \x03(\v2\r.util.PbLabelR\x06labels\x12+\n" +
	"\bcomments\x18\a \x03(\v2\x0f.util.PbCommentR\bcommentsB%Z#github.com/layfellow/todoister/utilb\x06proto3"

var (
	file_util_todoist_proto_rawDescOnce sync.Once
	file_util_todoist_proto_rawDescData []byte
)

func file_util_todoist_proto_rawDescGZIP() []byte {
	file_util_todoist_proto_rawDescOnce.Do(func() {
		file_util_todoist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_util_todoist_proto_rawDesc), len(file_util_todoist_proto_rawDesc)))
	})
	return file_util_todoist_proto_rawDescData
}

var file_util_todoist_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_util_todoist_proto_goTypes = []any{
	(*PbDuration)(nil),        // 0: util.PbDuration
	(*PbDue)(nil),             // 1: util.PbDue
	(*PbProject)(nil),         // 2: util.PbProject
	(*PbSection)(nil),         // 3: util.PbSection
	(*PbItem)(nil),            // 4: util.PbItem
	(*PbLabel)(nil),           // 5: util.PbLabel
	(*PbComment)(nil),         // 6: util.PbComment
	(*CachedTodoistData)(nil), // 7: util.CachedTodoistData
}
var file_util_todoist_proto_depIdxs = []int32{
	0, // 0: util.PbItem.duration:type_name -> util.PbDuration
	1, // 1: util.PbItem.due:type_name -> util.PbDue
	2, // 2: util.CachedTodoistData.projects:type_name -> util.PbProject
	3, // 3: util.CachedTodoistData.sections:type_name -> util.PbSection
	4, // 4: util.CachedTodoistData.items:type_name -> util.PbItem
	5, // 5: util.CachedTodoistData.labels:type_name -> util.PbLabel
	6, // 6: util.CachedTodoistData.comments:type_name -> util.PbComment
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_util_todoist_proto_init() }
func file_util_todoist_proto_init() {
	if File_util_todoist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_util_todoist_proto_rawDesc), len(file_util_todoist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_todoist_proto_goTypes,
		DependencyIndexes: file_util_todoist_proto_depIdxs,
		MessageInfos:      file_util_todoist_proto_msgTypes,
	}.Build()
	File_util_todoist_proto = out.File
	file_util_todoist_proto_goTypes = nil
	file_util_todoist_proto_depIdxs = nil
}
